# §
name: HypeFlexPunishments
version: 1.0
main: com.osx11.hypeflex.punishments.Main
commands:
  HFPunishments:
    description: 'Reloads plugin'
    usage: '§cUsage: /hfp'
    aliases: [HFPunishments, hfp]
  kick:
    description: 'Kicks player'
    usage: '§cUsage: /kick <player> [reason]'
  ban:
    description: 'Bans player'
    usage: '§cUsage: /ban [-f] <player> [reason]'
  banip:
    description: 'Bans player IP address'
    usage: '§cUsage: /banip [-f] <player> [reason] OR /banip <IP> [reason]'
  tempban:
    description: 'Bans player for specified time'
    usage: '§cUsage: /tempban [-f] <player> <time> [reason]'
  unban:
    description: 'Unbans player'
    usage: '§cUsage: /unban <player>'
  unbanip:
    description: 'Unbans player IP address'
    usage: '§cUsage: /unbanip <ip (or player)>'
  banlist:
    description: 'Shows banned players'
    usage: '§cUsage: /banlist'
  banlistip:
    description: 'Shows banned players IP'
    usage: '§cUsage: /banlistip'
  mute:
    description: 'Blocks players chat'
    usage: '§cUsage: /mute [-f] <player> [reason]'
  muteip:
    description: 'Blocks players ip chat'
    usage: '§cUsage: /muteip [-f] <player> [reason]'
  tempmute:
    description: 'Blocks players chat for specified time'
    usage: '§cUsage: /tempmute [-f] <player> <time> [reason]'
  unmute:
    description: 'Unmutes player'
    usage: '§cUsage: /unmute <player>'
  unmuteip:
    description: 'Unmutes players ip'
    usage: '§cUsage: /unmute <ip (or player)>'
  warn:
    description: 'Warn player'
    usage: '§cUsage: /warn <player> <reason>'
  warnlist:
    description: 'Shows all warns of player'
    usage: '§cUsage: /warnlist <player>'
  unwarn:
    description: 'Deletes players warn (delete all players warns if -a flag is specified)'
    usage: '§cUsage: /unwarn [-a] <player> <warn_id>'