name: HypeFlexPunishments
version: 1.0
main: com.osx11.hypeflex.punishments.Main
depend: [Vault]
commands:
  HFPunishments:
    description: 'Reloads plugin'
    usage: '§c/hfp'
    aliases: [HFPunishments, hfp]
  kick:
    description: 'Kicks player'
    usage: '§c/kick [-s] <player> [reason]'
  ban:
    description: 'Bans player'
    usage: '§c/ban [-f] [-s] <player> [reason]'
  banip:
    description: 'Bans player IP address'
    usage: '§c/banip [-f] [-s] <player> [reason] OR /banip <IP> [reason]'
  tempban:
    description: 'Bans player for specified time'
    usage: '§c/tempban [-f] [-s] <player> <time> [reason]'
  unban:
    description: 'Unbans player'
    usage: '§c/unban [-s] <player>'
  unbanip:
    description: 'Unbans player IP address'
    usage: '§c/unbanip [-s] <ip (or player)>'
  banlist:
    description: 'Shows banned players'
    usage: '§c/banlist'
  banlistip:
    description: 'Shows banned players IP'
    usage: '§c/banlistip'
  mute:
    description: 'Blocks players chat'
    usage: '§c/mute [-f] [-s] <player> [reason]'
  muteip:
    description: 'Blocks players ip chat'
    usage: '§c/muteip [-f] [-s] <player> [reason]'
  tempmute:
    description: 'Blocks players chat for specified time'
    usage: '§c/tempmute [-f] [-s] <player> <time> [reason]'
  unmute:
    description: 'Unmutes player'
    usage: '§c/unmute [-s] <player>'
  unmuteip:
    description: 'Unmutes players ip'
    usage: '§c/unmute [-s] <ip (or player)>'
  warn:
    description: 'Warn player'
    usage: '§c/warn [-f] [-s] <player> <reason>'
  warnlist:
    description: 'Shows all warns of player'
    usage: '§c/warnlist <player>'
    aliases: [warnlist, warns]
  unwarn:
    description: 'Deletes players warn (delete all players warns if -a flag is specified)'
    usage: '§c/unwarn [-a] <player> <warn_id>'
  pinfo:
    description: 'Shows information about player'
    usage: '§c/pinfo <player>'